### Listar produtos
GET http://localhost:5076/api/produto/listar

### Cadastrar de produtos
POST http://localhost:5076/api/produto/cadastrar
Content-Type: application/json

{
    "nome" : "TV",
    "descricao" : "47 polegadas",
    "preco" : 2500.00
}

### Buscar produto
GET http://localhost:5076/api/produto/buscar/1113bed60-2c68-46ff-b7e7-c25f654376e2

### Deletar produto
DELETE http://localhost:5076/api/produto/deletar/b9290772-a4e9-46a2-bfd8-42100df57baa

### Alterar produto
PUT http://localhost:5076/api/produto/alterar/b4f846b2-364b-41c0-a412-800169474d93
Content-Type: application/json

{
    "nome" : "TV Alterada",
    "descricao" : "50 polegadas",
    "preco" : 2800.00
}